### ISSUE TITLE
false negative

### ISSUE THREAD

**Issue by helmus** [mvdan/unparam#49] opened 2020-06-17 23:13 UTC
Is this a false negative ?

```
// +build !test

package main

import (
	"log"
)

func test(a func(tx int) error) {
	log.Print(a)
}

func main() {
	test(func(tx int) error {
                // tx is not used
		return nil
	})
	return
}
```
```
debug output: 
func test
  skip - dummy implementation
func main
func main$1
  skip - dummy implementation
```
If I just wanted to satisfy the interface, I would write this instead:

```
func main() {
	test(func(int) error {
                // tx is not used
		return nil
	})
	return
}
```
Or this
```
func main() {
	test(func(_ int) error {
                // tx is not used
		return nil
	})
	return
}
```

**Comment by mvdan** [comment] 2020-06-20 22:02
Hm. You could call it a false negative, but the tool is pretty conservative when a function's signature is fixed by the code. I would say this is working as intended. Imagine:

```
http.HandleFunc(func(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintln(w, "Hello world!")
})
```

If we implement your idea, this would be a warning, because `r` is unused. However, having to rename the request would be cumbersome and make the code less consistent with other http handler funcs:

```
http.HandleFunc(func(w http.ResponseWriter, _ *http.Request) {
    fmt.Fprintln(w, "Hello world!")
})
```

The aim of the tool is not to flag parameters which could lose their names - the aim is to find parameters that could be removed entirely. That's pretty well summarised by "unused", I think. In a way, your parameter *is* used - to satisfy a function signature.

**Comment by helmus** [comment] 2020-06-20 22:20
I see your point. However I would argue that parameter names are actually not part of the function signature. The signature is defined by the types only. If the variable is not used I really prefer _ or omitting since it documents that the function is not using it. Hope that argument makes sense

**Comment by mvdan** [comment] 2020-06-20 22:24
Yeah, that makes sense, but that feels like personal preference more than anything. A linter that tells you what parameters could be named `_` could exist, but that linter isn't unparam, because it does something quite different :)

**Closed by mvdan** 2020-06-20 22:24 UTC

**Comment by helmus** [comment] 2020-06-20 22:31
Would you be open to have the functionality available as an opt in
configuration?

**Comment by mvdan** [comment] 2020-06-20 22:33
I would say not. The feature you want is pretty easy to write as a separate linter, so it doesn't really benefit from being here.
