### ISSUE TITLE
Possible to ignore stubbed functions?

### ISSUE THREAD

**Issue by ansermino** [mvdan/unparam#39] opened 2019-04-11 21:38 UTC
Is there anyway I can ignore stubbed functions? Specifically when they return errors? Here's an example:
```
func futureFeature(x int, y int) (z int, err error) {
   _, _ = x, y
    return 0, nil
}
```
This will warn me that `err` is always nil. I don't want to change the function signature as that would take away from the benefits of stubbing. There is no interface this function is adhering to so it won't get ignored.

**Comment by mvdan** [comment] 2019-04-13 01:05
Stub functions should be skipped; does this still happen if you remove the `_, _ = x, y` line?

**Comment by ansermino** [comment] 2019-04-13 21:49
Then it warms me about the unused params. Is there a specific way it determines if a function is stubbed?

**Comment by mvdan** [comment] 2019-04-14 00:45
Sorry, I can't reproduce either problem.

```
$ cat f1.go
package p

func f(x int, y int) (z int, err error) {
        _, _ = x, y
        return 0, nil
}
$ unparam f1.go
$ cat f2.go
package p

func f(x int, y int) (z int, err error) {
        return 0, nil
}
$ unparam f2.go
```

Are you sure you're running the latest version from master?

**Comment by mvdan** [comment] 2019-04-21 05:58
No answer; closing.

**Closed by mvdan** 2019-04-21 05:58 UTC
Labels: needs info
