### ISSUE TITLE
unparam doesn't detect this offender

### ISSUE THREAD

**Issue by metaleap** [mvdan/unparam#6] opened 2017-04-09 01:55 UTC
[This one.](https://github.com/metaleap/go-util-dev/blob/ec248f261aa73150401a66b70d02a07156eeb251/dev.go#L85)

Back when I had it at the top of the file rather than the bottom, it did though! But now, zero output. My version is -- ah no `--version` flag but ~2-3 days fresh pretty much. I can't wait to learn the cause of *that* odd bug  😁

**Comment by bradleyfalzon** [comment] 2017-04-09 02:27
I'd say it's because the entire `Pretend` func is being optimised out. I can't explain why it would or wouldn't based on the location of the unused func though.

**Comment by metaleap** [comment] 2017-04-09 09:15
Hm wouldn't something like unparam be rather just an file AST-level tool? "Optimizing out" an exported module member would imply some global usage analysis, rather more work than would be necessary for such a tool

**Comment by metaleap** [comment] 2017-04-09 09:34
Just tried with that function being used in another that will never be "optimized out" because other packages import and use it.  As the Pretend func causes a side-effect (println), gc must never ditch it when it is called anywhere at all. Same faulty result (ie none), so that can't be it.

**Comment by mvdan** [comment] 2017-04-09 10:16
On the phone, so just two quick points to clarify:

* We don't just use the AST, that would be insane. We could do with just type info, but we use SSA which does quite a lot of work for us. For example, it already records where any variable is used, so it makes the initial finding of unused params a single line.
* SSA does ignore some funcs, like those that are unreachable (e.g. an unexported func that isn't used in its package). Not the case here though, I think.
* What I think is happening (and by design) is that we ignore that func as a stub. Funcs that have empty or near-empty bodies are ignored, because otherwise stub implementations (like to satisfy an interface but the method just panics) would be too many false positives. Try adding an if or a for or something, as any logic or non-trivial statement should take it out of the stub realm.

Re the last point, I probably need to explain this a bit in the README. And I know it leans on the safe side, but that's by design - I'd rather have false negatives than false positives.

**Comment by bradleyfalzon** [comment] 2017-04-09 10:36
I did look a little further, it seems to be actively skipping functions that match a custom type:

Minimal example

```
package foo

type t func(path string)

func f(str string) {
        println("")
}
```

Perhaps related to 4da8b086b7b483317d6d68b37f26e1ca003a9ae8 ? But I haven't looked much further.

**Comment by metaleap** [comment] 2017-04-09 10:39
@mvdan probably the *exact spec* of when a func qualifies as a "stub" might greatly add to the readme! (Icing on the cake would be either an option to print which stubs were ignored, or one to never skip "stubs" .. but then, icing, not the most pressing need  =)

**Comment by metaleap** [comment] 2017-04-09 11:02
Can confirm adding another unused arg causes the function to be reported. Well OK then! "Stub" I guess. Best put the rules of engagement in `--help` or `readme.md` going forward  =)

**Comment by bradleyfalzon** [comment] 2017-04-09 11:33
I would hope that there may be a better option than leaving it as is, in this case, the type came from an external package and was relatively simple so it matched functions that weren't meant to be matched.

As for the readme, check the commit I linked to, as there is a note about signatures there.

Are we certain we want this behaviour, it seems hard to detect and will match more than what's intended? Or perhaps I've misunderstood its usefulness.

**Comment by mvdan** [comment] 2017-04-10 11:29
Right, then it was the named func type that was making the tool ignore the func.

> Are we certain we want this behaviour, it seems hard to detect and will match more than what's intended? 

As with other rules, this is the tool being conservative. If not, it would have false positives like:

```
type WalkFunc func(path string, info *os.FileInfo)

func walk(path string, info *os.FileInfo) {
    println(path)
}
```

You could say that the func should be `func walk(path string, _ *os.FileInfo)`, but you're getting into a territory where the tool is becoming more annoying than useful.

Back to your minimal example:

```
package foo

type t func(path string) // if this is removed, str is flagged.

func f(str string) {
        println("")
}
```

The tool could be made smarter (read: more complex) to notice that `f` is never used as type `t`, since they are both unexported and we can tell from the package's source code. I haven't done that simply because I was lazy. I suspect the benefit would be little, but it wouldn't bring false positives.

I'm going to open an issue about this and close this one.

**Closed by mvdan** 2017-04-10 11:29 UTC
