### ISSUE TITLE
false positive with func called via reflect.ValueOf(x).Call

### ISSUE THREAD

**Issue by dvic** [mvdan/unparam#23] opened 2018-02-27 22:52 UTC
Hi,

I have the following function:

```
	g.EXPECT().Begin(gomock.Any()).Times(errorTask).DoAndReturn(
		func(_ context.Context) (db.Tx, error) {
			...
			return tx, nil
		},
	)
```

On my mac `unparam` does not report any problems but on travis ci it reports `parameter (*suite).TestSuccess$1 - result 1 (error) is always nil`. I use [retool](https://github.com/twitchtv/retool) to pin the latest version of this writing (2b8063fd56cd7096ee6d62783b62a87a832b06e7). Any idea what might be causing this discrepancy? The tool should not lint this function in the first place because it is unnamed right?

**Comment by mvdan** [comment] 2018-02-28 09:58
> The tool should not lint this function in the first place because it is unnamed right?

The tool does check all defined functions. It does not look at whether they were named or not. It only discards certain patterns, like stubs and init funcs.

I'm not sure why the platform should mean a discrepancy. Are you absolutely sure that you're running the same version on both platforms? I recently did some changes that add lots of "result X (error) is always nil" warnings.

Another potential reason would be build tags. The tool loads your packages only once, with the host's GOOS and GOARCH. So if there's a warning involving a file that will only be built on mac, the warning will only show on mac.

Aside from those two ideas, I can't do much else without a way to reproduce the issue.

**Comment by dvic** [comment] 2018-02-28 10:00
Thanks! I'll look into it and try to see if I can reproduce the issue in a self-contained example. I'll keep you posted.

**Comment by dvic** [comment] 2018-02-28 10:18
I just tried an example and that did not give problems on TravisCI: https://github.com/dvic/unparam-travis-issue/blob/master/main.go

I'll try now to use `--debug` on my private repo and see what the difference is when running it on TravisCI and locally.

**Comment by dvic** [comment] 2018-02-28 11:15
I have found the problem. It is indeed a difference in version. It turns out that locally I am using the version installed by `gometalinter` (which is vendored to 6b9a9bf4cdf71fae79104529ee3f16148302cc71) and on TravisCI, the latest version is installed.

I did however manage to reproduce it with a new example: https://travis-ci.org/dvic/unparam-travis-issue/builds/347220554

This returns `main_test.go:18:33: TestSomething$1 - result 1 (error) is always nil`.

What do you think? Should this be considered as a false positive? I guess it should right? Because the mock interface expects a function that matches exactly that signature, I can't avoid that. I'm not sure however how difficult it is to catch these kind of situations.

Anyways, I'm glad I found the reason for the difference, thanks for your help and the great tool!

**Comment by mvdan** [comment] 2018-02-28 11:18
> Because the mock interface expects a function that matches exactly that signature, I can't avoid that. I'm not sure however how difficult it is to catch these kind of situations.

Yes, that does sound like a false positive. And yes, it is tricky to catch all of these :)

Re-purposing the issue. Thanks for taking the time to file this!

**Comment by mvdan** [comment] 2018-02-28 22:11
@dvic you might be happy to know that your sample code also uncovered a go/types bug :) https://github.com/golang/go/issues/24182

**Comment by mvdan** [comment] 2018-02-28 22:20
Also, this is turning out to be more subtle than I thought.

> Because the mock interface expects a function that matches exactly that signature

Not exactly true:

    func (c *Call) DoAndReturn(f interface{}) *Call { ... }

In other words, the signature is required at run-time, not statically. I only avoid these false positives statically, when I know that a specific func type is required.

I only see two possibilities. The first, and cleanest, is to also ignore funcs that are converted to `interface{}`. Because once that happens, they could in theory be required to be of any signature.

The other, and more complex, is to detect how `DoAndReturn` is using that `interface{}`. However, I suspect this option would be a lot of extra work and code for little gain.

I'll try the first, and see if it removes any good warnings on my current testing corpus.

**Comment by mvdan** [comment] 2018-03-01 10:49
So it turns out that we are already doing the second option, with minimal effort, thanks to the callgraph package. That is, if a func gets converted to `interface{}` then asserted back to func type and called, the callgraph package keeps track of all that and tells us.

We already catch this instance of the func being type cast, and skip the func in that case. But callgraph seems to break down with complex uses of `reflect`, which is the case with `gomock`: https://github.com/golang/go/issues/24196

Let's see what Alan thinks of it. Hopefully, this is simply a bug in the callgraph building algorithms, and the fix on my side is trivial. For the time being, I'll add a test case for the already-working simpler cases.

**Comment by mvdan** [comment] 2018-03-01 10:52
Also, slight clarification - what keeps track of the func being passed as `interface{}` and then being type-cast back to a func type is `go/ssa`, not `go/callgraph`. We bail with the former in unparam, not with the latter. This method doesn't work with `reflect.ValueOf` and `reflect.Call` because they're just regular func calls, not special statements and expressions like the `v.(func(someArg))` type assertion.

So, for the `reflect` case, we do need to use callgraph to get a deeper analysis of what is going on.

**Comment by dvic** [comment] 2018-03-01 10:55
Clear, thanks for the explanation! I'm using gometalinter so I can manually ignore these corner cases.

**Comment by mvdan** [comment] 2019-01-24 12:52
I'm starting to rely less and less on the callgraph package, for reasons like this one. This should be fixed now; please shout if you still find any false positives.

**Closed** 2019-01-24 12:52 UTC
